spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: security
  jpa:
    hibernate:
      ddl-auto: update
  security:
    key: ${JWT_SECURITY_KEY}
    login-success-uri: ${LOGIN_SUCCESS_URI}
    apple:
      client-id: ${APPLE_CLIENT_ID}
      redirect-uri: ${APPLE_REDIRECT_URI}
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
logging:
  level:
    root: info