spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: security
  jpa:
    hibernate:
      ddl-auto: update
  security:
    key: ${JWT_SECURITY_KEY}
    google:
      client-id: ${GOOGLE_CLIENT_SECRET}
      client-secret: ${GOOGLE_CLIENT_ID}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
      login-success-uri: ${GOOGLE_LOGIN_SUCCESS_URI}
logging:
  level:
    root: info